const FETCH_PRODUCTS = "product/FETCH_PRODUCTS";
const FETCH_PRODUCTS_COMPLETED = "product/FETCH_PRODUCTS_COMPLETED";
const FETCH_PRODUCTS_FAILED = "product/FETCH_PRODUCTS_FAILED";

export default {
    FETCH_PRODUCTS,
    FETCH_PRODUCTS_COMPLETED,
    FETCH_PRODUCTS_FAILED,
};
