const FETCH_PRODUCTS = "product/FETCH_PRODUCTS";
const FETCH_PRODUCTS_COMPLETED = "product/FETCH_PRODUCTS_COMPLETED";
const FETCH_PRODUCTS_FAILED = "product/FETCH_PRODUCTS_FAILED";
const CREATE_PRODUCT = "product/CREATE_PRODUCT";
const CREATE_PRODUCT_COMPLETED = "product/CREATE_PRODUCT_COMPLETED";
const CREATE_PRODUCT_FAILED = "product/CREATE_PRODUCT_FAILED";

export default {
    FETCH_PRODUCTS,
    FETCH_PRODUCTS_COMPLETED,
    FETCH_PRODUCTS_FAILED,
    CREATE_PRODUCT,
    CREATE_PRODUCT_COMPLETED,
    CREATE_PRODUCT_FAILED,
};
