const GET_SITEMAP = "sitemap/GET_SITEMAP";
const GET_SITEMAP_FAILED = "sitemap/GET_SITEMAP_FAILED";
const GET_SITEMAP_COMPLETED = "sitemap/GET_SITEMAP_COMPLETED";
const ADD_CATEGORY = "sitemap/ADD_CATEGORY";
const ADD_CATEGORY_FAILED = "sitemap/ADD_CATEGORY_FAILED";
const ADD_CATEGORY_COMPLETED = "sitemap/ADD_CATEGORY_COMPLETED";

export default {
    GET_SITEMAP,
    GET_SITEMAP_FAILED,
    GET_SITEMAP_COMPLETED,
    ADD_CATEGORY,
    ADD_CATEGORY_FAILED,
    ADD_CATEGORY_COMPLETED,
};
