const GET_SITEMAP = "sitemap/GET_SITEMAP";
const GET_SITEMAP_FAILED = "sitemap/GET_SITEMAP_FAILED";
const GET_SITEMAP_COMPLETED = "sitemap/GET_SITEMAP_COMPLETED";

export default {
    GET_SITEMAP,
    GET_SITEMAP_FAILED,
    GET_SITEMAP_COMPLETED,
};
