const GET_SITEMAP = "sitemap/GET_SITEMAP";
const GET_SITEMAP_FAILED = "sitemap/GET_SITEMAP_FAILED";
const GET_SITEMAP_COMPLETED = "sitemap/GET_SITEMAP_COMPLETED";
const ADD_CATEGORY = "sitemap/ADD_CATEGORY";
const ADD_CATEGORY_FAILED = "sitemap/ADD_CATEGORY_FAILED";
const ADD_CATEGORY_COMPLETED = "sitemap/ADD_CATEGORY_COMPLETED";
const EDIT_CATEGORY = "sitemap/EDIT_CATEGORY";
const EDIT_CATEGORY_COMPLETED = "sitemap/EDIT_CATEGORY_COMPLETED";
const EDIT_CATEGORY_FAILED = "sitemap/EDIT_CATEGORY_FAILED";
const REMOVE_CATEGORY = "sitemap/REMOVE_CATEGORY";
const REMOVE_CATEGORY_FAILED = "sitemap/REMOVE_CATEGORY_FAILED";
const REMOVE_CATEGORY_COMPLETED = "sitemap/REMOVE_CATEGORY_COMPLETED";
const REMOVE_IMAGE = "sitemap/REMOVE_IMAGE";
const ADD_SUBCATEGORY = "sitemap/ADD_SUBCATEGORY";
const ADD_SUBCATEGORY_FAILED = "sitemap/ADD_SUBCATEGORY_FAILED";
const ADD_SUBCATEGORY_COMPLETED = "sitemap/ADD_SUBCATEGORY_COMPLETED";
const EDIT_SUBCATEGORY = "sitemap/EDIT_SUBCATEGORY";
const EDIT_SUBCATEGORY_FAILED = "sitemap/EDIT_SUBCATEGORY_FAILED";
const EDIT_SUBCATEGORY_COMPLETED = "sitemap/EDIT_SUBCATEGORY_COMPLETED";
const REMOVE_SUBCATEGORY = "sitemap/REMOVE_SUBCATEGORY";
const REMOVE_SUBCATEGORY_FAILED = "sitemap/REMOVE_SUBCATEGORY_FAILED";
const REMOVE_SUBCATEGORY_COMPLETED = "sitemap/REMOVE_SUBCATEGORY_COMPLETED";

const ADD_SECTION = "sitemap/ADD_SECTION";
const ADD_SECTION_FAILED = "sitemap/ADD_SECTION_FAILED";
const ADD_SECTION_COMPLETED = "sitemap/ADD_SECTION_COMPLETED";
const EDIT_SECTION = "sitemap/EDIT_SECTION";
const EDIT_SECTION_COMPLETED = "sitemap/EDIT_SECTION_COMPLETED";
const EDIT_SECTION_FAILED = "sitemap/EDIT_SECTION_FAILED";
const REMOVE_SECTION = "sitemap/REMOVE_SECTION";
const REMOVE_SECTION_FAILED = "sitemap/REMOVE_SECTION_FAILED";
const REMOVE_SECTION_COMPLETED = "sitemap/REMOVE_SECTION_COMPLETED";

export default {
    GET_SITEMAP,
    GET_SITEMAP_FAILED,
    GET_SITEMAP_COMPLETED,
    ADD_CATEGORY,
    ADD_CATEGORY_FAILED,
    ADD_CATEGORY_COMPLETED,
    EDIT_CATEGORY,
    EDIT_CATEGORY_COMPLETED,
    EDIT_CATEGORY_FAILED,
    REMOVE_CATEGORY,
    REMOVE_CATEGORY_FAILED,
    REMOVE_CATEGORY_COMPLETED,
    REMOVE_IMAGE,
    ADD_SUBCATEGORY,
    ADD_SUBCATEGORY_FAILED,
    ADD_SUBCATEGORY_COMPLETED,
    EDIT_SUBCATEGORY,
    EDIT_SUBCATEGORY_FAILED,
    EDIT_SUBCATEGORY_COMPLETED,
    REMOVE_SUBCATEGORY,
    REMOVE_SUBCATEGORY_FAILED,
    REMOVE_SUBCATEGORY_COMPLETED,
    ADD_SECTION,
    ADD_SECTION_FAILED,
    ADD_SECTION_COMPLETED,
    EDIT_SECTION,
    EDIT_SECTION_FAILED,
    EDIT_SECTION_COMPLETED,
    REMOVE_SECTION,
    REMOVE_SECTION_FAILED,
    REMOVE_SECTION_COMPLETED,
};
